// 候補の出所一致・手動への復帰・明示確認まで保存しないことを検証する。
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const source = fs.readFileSync(path.join(__dirname, '../../static/admin/admin.js'), 'utf8');
const modalCode = source.slice(source.indexOf('const _cropModal = {'), source.indexOf('_cropModal.init();'));
const helpers = source.slice(source.indexOf('function _validatedCropSuggestion('), source.indexOf('/**', source.indexOf('function _validatedCropSuggestion(')));
let saves = 0;
const context = vm.createContext({Number, URL, document: {body: {style: {}}, createElement: tag => ({tag})}, apiFetch: () => { saves++; }});
vm.runInContext(modalCode + helpers + '\nglobalThis.modal = _cropModal; globalThis.validate = _validatedCropSuggestion; globalThis.showEvidence = _showRecognitionEvidence;', context);
const candidate = {left: .1, top: .1, right: .9, bottom: .9, source_image_url: 'https://example.test/a.png'};
assert.equal(context.validate(candidate, 'https://example.test/b.png'), null);
for (const left of [NaN, Infinity, true, '0.1', -1]) {
  assert.equal(context.validate({...candidate, left}, candidate.source_image_url), null);
}
assert.equal(context.validate(null, candidate.source_image_url), null);
const hint = {};
Object.assign(context.modal, {img: {}, el: {querySelector: () => hint}, selEl: {style: {}}, confirmBtn: {}, suggestBtn: {}, resultEl: {}});
context.modal.open(1, {}, candidate.source_image_url, candidate);
assert.equal(context.modal._sel.left, .1);
assert.equal(context.modal.selEl.hidden, false);
assert.equal(context.modal.confirmBtn.disabled, false);
assert.match(hint.textContent, /候補枠/);
assert.equal(saves, 0);
context.modal.close();
assert.equal(saves, 0);
context.modal.open(2, {}, candidate.source_image_url);
assert.equal(context.modal._sel, null);
assert.equal(context.modal.selEl.hidden, true);
assert.equal(context.modal.confirmBtn.disabled, true);
context.modal.overlay = {getBoundingClientRect: () => ({left: 0, top: 0, width: 100, height: 100})};
context.modal._onDown({clientX: 10, clientY: 10, preventDefault() {}});
context.modal._onMove({clientX: 80, clientY: 90});
context.modal._onUp();
assert.equal(context.modal._sel.right, .8);
assert.equal(context.modal.confirmBtn.disabled, false);
assert.equal(saves, 0);
const panel = {children: [], replaceChildren() { this.children = []; }, appendChild(child) {this.children.push(child);}, get childElementCount() {return this.children.length;}};
const form = {querySelector: () => panel};
context.showEvidence({recognition_review: {status: 'needs_review', reason: '<img src=x>'}, release_date_evidence: {status: 'verified', source_url: 'https://www.yugioh-card.com/japan/products/test/'}}, form);
assert.match(panel.children[1].textContent, /抽出時の数値再読：要確認/);
assert.match(panel.children[1].textContent, /<img src=x>/);
assert.equal(panel.children[2].tag, 'a');
context.showEvidence({release_date_evidence: {status: 'needs_review', source_url: 'https://www.yugioh-card.com.evil.test/japan/products/test/'}}, form);
assert.equal(panel.children.length, 1);
context.showEvidence({}, form);
assert.equal(panel.hidden, true);
console.log('admin_crop_check: 候補・手動操作・根拠表示の検証成功');
const snapshotCard = {product_name: '商品A', release_date: '2026-10-31', release_date_evidence: {status: 'verified', product_name: '商品A', release_date: '2026-10-31'}};
context.showEvidence(snapshotCard, form);
assert.doesNotMatch(panel.children[0].textContent, /手動変更あり/);
context.showEvidence({...snapshotCard, release_date: '2025-10-31'}, form);
assert.match(panel.children[0].textContent, /手動変更あり・現在値は未照合/);
context.showEvidence(snapshotCard, {querySelector: selector => selector === '.recognition-evidence' ? panel : selector === '[name="release_date"]' ? {value: '2027-10-31'} : null});
assert.match(panel.children[0].textContent, /手動変更あり・現在値は未照合/);

(async () => {
  let respond;
  let requests = 0;
  context.apiFetch = () => {requests++; return new Promise(resolve => {respond = resolve;});};
  const response = {ok: true, json: async () => ({ok: true, crop_suggestion: candidate})};
  context.modal.open(3, {}, candidate.source_image_url);
  const pending = context.modal._suggest();
  await context.modal._suggest();
  assert.equal(requests, 1);
  respond(response);
  await pending;
  assert.equal(context.modal._sel.left, .1);
  assert.equal(saves, 0);
  const stale = context.modal._suggest();
  context.modal.close();
  context.modal.open(4, {}, candidate.source_image_url);
  respond(response);
  await stale;
  assert.equal(context.modal._sel, null);
  const manuallyChanged = context.modal._suggest();
  context.modal._onDown({clientX: 20, clientY: 20, preventDefault() {}});
  context.modal._onMove({clientX: 70, clientY: 70});
  context.modal._onUp();
  respond(response);
  await manuallyChanged;
  assert.equal(context.modal._sel.left, .2);
  assert.equal(saves, 0);
  console.log('admin_crop_check: 再生成・連打防止・遅延応答・手動変更表示の検証成功');
})().catch(error => {console.error(error); process.exitCode = 1;});
